services:
  - name: mern-backend
    type: web
    runtime: node
    rootDir: backend  # ✅ Set backend folder as root (if backend is inside `/backend`)
    buildCommand: npm install
    startCommand: node server.js  # ✅ Change if your entry file is different
    envVars:
      - key: MONGO_URI
        sync: false  # Manually set in Render Dashboard
      - key: JWT_SECRET
        sync: false  # Manually set in Render Dashboard
      - key: CLIENT_URL
        value: https://quesaikamal.netlify.app/  # Update after frontend deployment
